# ***Iteración de matriz***

> ###  ⚠️ ***Iterando arreglos: 1-D***

Iterar significa pasar por los elementos uno por uno.

Como tratamos con matrices multidimensionales en numpy, podemos hacerlo usando el forbucle básico de python.

Si iteramos en una matriz 1-D, pasará por cada elemento uno por uno.

In [1]:
#Iterar sobre los elementos de la siguiente matriz 1-D:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


> ###  ⚠️ ***Iterando arreglos 2-D***

En una matriz 2D, recorrerá todas las filas.

In [2]:
#Iterar sobre los elementos de la siguiente matriz 2-D:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


Nota: Si iteramos en una matriz n -D, pasará por la dimensión n-1 una por una.

Para devolver los valores reales, los escalares, tenemos que iterar las matrices en cada dimensión.

In [4]:
#Iterar en cada elemento escalar de la matriz 2-D:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


> ###  ⚠️ ***Iterando arreglos 3-D***

En una matriz 3D, pasará por todas las matrices 2D.

In [5]:
#Iterar sobre los elementos de la siguiente matriz 3-D:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


Para devolver los valores reales, los escalares, tenemos que iterar las matrices en cada dimensión.

In [6]:
#Iterar hasta los escalares:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


> ###  ⚠️ ***Iterating Arrays Using nditer()***

La función nditer()es una función de ayuda que se puede utilizar desde iteraciones muy básicas hasta muy avanzadas. Resuelve algunos problemas básicos que enfrentamos en la iteración, analicémoslo con ejemplos.

> Iterando en cada elemento escalar

En los bucles básicos for, al iterar a través de cada escalar de una matriz, necesitamos usar n for bucles que pueden ser difíciles de escribir para matrices con una dimensionalidad muy alta.

In [7]:
#Iterar a través de la siguiente matriz 3-D:

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


> ###  ⚠️ ***Matriz de iteración con diferentes tipos de datos***

Podemos usar op_dtypesel argumento y pasarle el tipo de datos esperado para cambiar el tipo de datos de los elementos durante la iteración.

NumPy no cambia el tipo de datos del elemento en el lugar (donde el elemento está en la matriz), por lo que necesita otro espacio para realizar esta acción, ese espacio adicional se llama búfer, y para habilitarlo nditer()pasamos flags=['buffered'].

In [8]:
#Iterar a través de la matriz como una cadena:

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


> ###  ⚠️ ***Iterando con diferente tamaño de paso***

Podemos usar filtrado y seguido de iteración.

In [9]:
#Iterar a través de cada elemento escalar de la matriz 2D omitiendo 1 elemento:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


> ###  ⚠️ ***Iteración enumerada usando ndenumerate()***

Enumeración significa mencionar el número de secuencia de algo uno por uno.

A veces requerimos el índice correspondiente del elemento durante la iteración, el ndenumerate()método se puede usar para esos casos de uso.

In [10]:
#Enumerar en los siguientes elementos de matrices 1D:

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [11]:
#Enumere los siguientes elementos de la matriz 2D:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
