# ***Matriz de unión NumPy***

> ###  ⚠️ ***Unirse a matrices NumPy***

Unirse significa poner el contenido de dos o más matrices en una sola matriz.

En SQL unimos tablas en base a una clave, mientras que en NumPy unimos matrices por ejes.

Pasamos una secuencia de matrices que queremos unir a la concatenate()función, junto con el eje. Si el eje no se pasa explícitamente, se toma como 0.

In [1]:
#Unir dos matrices

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [2]:
#Une dos matrices 2-D a lo largo de las filas (eje = 1):

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


> ###  ⚠️ ***Unión de matrices mediante funciones de pila***

El apilamiento es lo mismo que la concatenación, la única diferencia es que el apilamiento se realiza a lo largo de un nuevo eje.

Podemos concatenar dos matrices 1-D a lo largo del segundo eje, lo que daría como resultado colocarlas una sobre la otra, es decir. apilado.

Pasamos una secuencia de matrices que queremos unir al stack()método junto con el eje. Si el eje no se pasa explícitamente, se toma como 0.

In [3]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


> ###  ⚠️ ***Apilamiento a lo largo de las filas***

NumPy proporciona una función de ayuda: hstack() para apilar a lo largo de las filas.

In [4]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


> ###  ⚠️ ***Apilamiento a lo largo de las columnas***

NumPy proporciona una función de ayuda: vstack()  apilar a lo largo de las columnas.

In [5]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


> ###  ⚠️ ***Apilamiento a lo largo de la altura (profundidad)***

NumPy proporciona una función de ayuda: dstack() apilar a lo largo de la altura, que es lo mismo que la profundidad.

In [7]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
