# ***Arreglos de búsqueda NumPy***

> ###  ⚠️ ***Buscando arreglos***

Puede buscar en una matriz un determinado valor y devolver los índices que obtienen una coincidencia.

Para buscar una matriz, utilice el where()método.

In [1]:
#Encuentre los índices donde el valor es 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


El ejemplo anterior devolverá una tupla:(array([3, 5, 6],)

Lo que significa que el valor 4 está presente en el índice 3, 5 y 6

In [2]:
#Encuentre los índices donde los valores son pares:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [4]:
#Encuentre los índices donde los valores son impares:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


> ###  ⚠️ ***Búsqueda ordenada***

Hay un método llamado searchsorted()que realiza una búsqueda binaria en la matriz y devuelve el índice donde se insertaría el valor especificado para mantener el orden de búsqueda.

Nota: Se supone que el searchsorted()método se utiliza en matrices ordenadas.

In [6]:
#Encuentre los índices donde se debe insertar el valor 7:

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


Ejemplo explicado: El número 7 debe insertarse en el índice 1 para mantener el orden de clasificación.

El método inicia la búsqueda desde la izquierda y devuelve el primer índice donde el número 7 ya no es mayor que el siguiente valor.

> Buscar desde el lado derecho

De forma predeterminada, se devuelve el índice más a la izquierda, pero podemos dar side='right'para devolver el índice más a la derecha en su lugar.

In [7]:
#Encuentre los índices donde se debe insertar el valor 7, comenzando desde la derecha:

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


Ejemplo explicado: El número 7 debe insertarse en el índice 2 para mantener el orden de clasificación.

El método inicia la búsqueda desde la derecha y devuelve el primer índice donde el número 7 ya no es menor que el siguiente valor.

> Valores múltiples

Para buscar más de un valor, utilice una matriz con los valores especificados.

In [8]:
#Encuentre los índices donde se deben insertar los valores 2, 4 y 6:

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


El valor devuelto es una matriz: [1 2 3]contiene los tres índices donde 2, 4, 6 se insertarían en la matriz original para mantener el orden.