# ***Arreglos de clasificación NumPy***

> ###  ⚠️ ***Clasificación de matrices***

Clasificar significa poner elementos en una secuencia ordenada .

Secuencia ordenada es cualquier secuencia que tiene un orden correspondiente a los elementos, como numérico o alfabético, ascendente o descendente.

El objeto NumPy ndarray tiene una función llamada sort(), que ordenará una matriz específica.

In [1]:
#Ordenar la matriz:

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


Nota: este método devuelve una copia de la matriz, dejando la matriz original sin cambios.

También puede ordenar matrices de cadenas o cualquier otro tipo de datos:

In [2]:
#Ordenar la matriz alfabéticamente:

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [3]:
#Ordenar una matriz booleana:

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


> ###  ⚠️ ***Ordenar una matriz 2-D***

Si usa el método sort() en una matriz 2-D, ambas matrices se ordenarán:

In [4]:
#Ordenar una matriz 2-D:

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
