# ***Creacion de matrices (Array)***

💡 ***El objeto de matriz en NumPy se llama (ndarray).***

❓ ***¿Que significa ndarray? n-dimensional-array***

> ###  ⚠️ ***Como crear un objeto (ndarray) osea una matriz***

> ☢️ ***Usando la funcion:*** *array()*

        Estructura: variable_nueva = np.array([elemento1,elemento2,elemento3])

In [3]:
#Importamos numpy para poder utilizar su libreria
import numpy as np
#Creamos un objeto (ndarray): variable_nueva = np.array([elemento1,elemento2,elemento3])
arr = np.array([1, 2, 3, 4, 5])
#Imprimimos
print(arr)
#Imprimimos el tipo de dato
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


> ☢️ ***Como convertir una lista o tupla a un ndarray***

💡 ***Usamos el metodo: array()***

🟢 ***Con este metodo convertimos cualquier objeto similar a una matriz como una lista o tupla a un ndarray***

In [4]:
#Convertimos una tupla a ndarray
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [5]:
#Convertimos una lista a ndarray
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


> ###  ⚠️ ***Dimensiones en matrices (arrays)***

❓ ***Te puedes dar cuenta de cuantas dimensiones tiene por la cantidad de [ ]***

> ☢️ ***0-D Arrays***

💡 ***Es una matriz con solo un elemento, Cada valor en una matriz es una matriz 0-D***

🟢 ***No tiene ningun par de [ ]***

In [8]:
#Cree una matriz 0-D con valor 42
arr = np.array(42)
print(arr)
print(arr.ndim)

42
0


> ☢️ ***1-D Arrays***

💡 ***Es una matriz que tiene dentro de ella como sus elementos matrices 0-D***

🟢 ***Tiene 1 par de [ ]***

In [9]:
#Cree una matriz 1-D: que contenga los valores 1,2,3,4,5:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


> ☢️ ***2-D Arrays***

💡 ***Es una matriz que tiene dentro de ella como sus elementos matrices 1-D.***

🟢 ***Se utilizan a menudo para representar matrices o tensores de segundo orden.***

🟢 ***Tiene 2 pares de [ ] mas el [ ] que los encierra***

In [10]:
#Cree una matriz 2-D que contenga dos matrices con los valores 1,2,3 y 4,5,6:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


> ☢️ ***3-D Arrays***

💡 ***Es una matriz que tiene dentro de ella como sus elementos matrices 2-D.***

🟢 ***Estos se utilizan a menudo para representar un tensor de tercer orden.***

In [11]:
#Cree una matriz 3D con dos matrices 2D, ambas con dos matrices con los valores 1,2,3 y 4,5,6:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


> ###  ⚠️ ***Como verificar el numero de dimensiones que tiene una matriz (array)***

💡 ***Usamos el atributo: ndim***

❓ ***Este atributo devuelve un número entero que nos dice cuántas dimensiones tiene la matriz.***

In [12]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


> ###  ⚠️ ***Como especificar la cantidad de dimensiones que queremos que tenga nuestra matriz (array)***

💡 ***Usamos el parametro: ndmin***

❓ ***Sirve para definir el número de dimensiones que queremos***

🟢 ***Una matriz puede tener cualquier número de dimensiones.***

In [12]:
#Cree una matriz con 5 dimensiones y verifique que tenga 5 dimensiones:
#En esta matriz, la dimensión más interna (quinta dimensión) tiene 4 elementos, la cuarta dimensión tiene 1 elemento que es el vector, 
#la tercera dimensión tiene 1 elemento que es la matriz con el vector, la segunda dimensión tiene 1 elemento 
#que es una matriz 3D y 1st dim tiene 1 elemento que es una matriz 4D.
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('Cantidad de dimensiones: ', arr.ndim)

[[[[[1 2 3 4]]]]]
Cantidad de dimensiones:  5
