# ***Slicing (Corte) de una matriz ((ndarray)) en NumPy***

> ###  ⚠️ ***Como cortar matrices (Slicing arrays): 1-D***

❓ ***Cortar en python significa tomar elementos de un índice dado a otro índice dado.***

        Estructura para cortar SIN saltos: [#Posicion_inical:#Posicion_final]

        Estructura para cortar CON saltos: [#Posicion_inical:#Posicion_final:#Salto]

❗ ***El resultado incluye siempre el elemento de la posicon final pero nunca incluye el elemento de la poscion final***

> 🟢 ***Hay 3 diferentes casos:***

➖ ***Si no pasamos #Posicion_inical se considera 0.***

In [3]:
#Cortar elementos desde el principio hasta el índice 4 (no incluido):
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4]) #(0:4)

[1 2 3 4]


➖ ***Si no pasamos #Posicion_final se ejecutara de la #Posicion_inical que tomes hasta el ultimo elemento.***

In [2]:
#Corta elementos desde el índice 4 hasta el final de la matriz:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:]) #(4:0)

[5 6 7]


➖ ***Si no pasamos el #Salto se considera el salto como de 1.***

In [2]:
import numpy as np
#Divide los elementos del índice 1 al índice 5 de la siguiente matriz:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5]) #(1:5:1)

[2 3 4 5]


➖ ***Con #Salto especificado.***

In [3]:
#Devuelve cualquier otro elemento del índice 1 al índice 5:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2]) #Indicas que salte cada 2 elementos

[2 4]


In [4]:
#Devuelve todos los demás elementos de toda la matriz:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2]) #(0:0:2)

[1 3 5 7]


> ###  ⚠️ ***Como cortar matrices en negativo (Slicing arrays): 1-D***

💡 ***Use el operador (-) para referirse a una posicion desde el final***

❗ ***El conteo de las posiciones de los elementos en negativo inicia en -1 y no en 0***

In [5]:
#Cortar desde el índice 3 desde el final hasta el índice 1 desde el final:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1]) #(5:#Posicion_final)

[5 6]


> ###  ⚠️ ***Como cortar matrices (Slicing arrays): 2-D***

💡 ***Estructura: arr[#Fila, #Posicion_inicial:Posicion_final]***

> 🟢 ***Casos:***

➖ ***arr[#Fila, #Posicion_inicial:Posicion_final]***

In [8]:
#Desde el segundo elemento, corte los elementos del índice 1 al índice 4 (no incluido):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [9]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0, 1:4])

[2 3 4]


➖ ***arr[#Fila_Inicial:Fila_final,#Posicion_inicial]***

In [14]:
#De ambos elementos, devuelva la posicion 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2]) #Tomara las filas 0 y 1, y tomara a los elementos de la posicon 2 de cada fila

[3 8]


➖ ***arr[#Fila_Inicial:Fila_final,#Posicion_inicial:#Posicion_final]***

In [11]:
#De ambos elementos, corte el índice 1 al índice 4 (no incluido), esto devolverá una matriz 2-D:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4]) #Tomara la fila 0 y la 1 y tomara los elementos de ambas filas de la poscion inial 1 hasta la 4 sin incluirla

[[2 3 4]
 [7 8 9]]
