# ***Tipos de datos en NumPy***

🟡 ***Python por defecto tiene estos tipos de datos: interger, float, boolean, strings, complex***

☢️ ***Pero NumPy añade mas tipos de datos, se refiere a los tipos de datos mediante solamente 1 caracter:***

        i - integer
        b - boolean
        u - unsigned integer (Entero sin signo)
        f - float
        c - complex float
        m - timedelta
        M - datetime
        O - object
        S - string
        U - unicode string
        V - fixed chunk of memory for other type ( void )

> ###  ⚠️ ***Como saber el tipo de dato de un array (Matriz)***

💡 ***Usamos el atributo: dtype***

❓ ***Este atributo devuelve el tipo de datos de la matriz (array)***

In [1]:
#Obtenga el tipo de datos de un objeto de matriz:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [3]:
arr = np.array([True, False])
print(arr.dtype)

bool


In [2]:
arr = np.array(["Hola", "Adios", "Daniel"])
print(arr.dtype)

<U6


> ###  ⚠️ ***Como crear una matriz (array) con un tipo de dato definido***

💡 ***Usamos la funcion: array()***

❓ ***Esta funcion se usa para crear matrices, dentro de la funcion ponemos como parametro (Es opcional, no obligatorio) el parametro: dtype***

☢️ ***Este parametro nos permite definir el tipo de datos esperado de los elementos de la matriz.***

        Estructura: array(dtype = "tipo_dato")


In [10]:
#Cree una matriz con una cadena de tipo de datos:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [13]:
#Cree una matriz con un tipo de datos entero de 4 bytes:
arr = np.array([1, 2, 3, 4], dtype='i')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


> ###  ⚠️ ***¿Qué pasa si un valor no se puede convertir?***

☢️ ***Si se proporciona un tipo de dato en el que los elementos no se pueden convertir, NumPy generará un ValueError.***

❓ ***ValueError: en Python, ValueError se genera cuando el tipo de parametro pasado a una función es inesperado/incorrecto.***

In [14]:
#Una cadena no entera como 'a' no se puede convertir a entero (generará un error):
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

> ###  ⚠️ ***Conversión de tipos de datos en arreglos existentes***

💡 ***Para cambiar el tipo de datos de una matriz existente debemos de crear una copia de la matriz original con el metodo: astype***

❓ ***Esta funcion crea una copia de la matriz original y le permite especificar el tipo de datos como parámetro.***

        Estructura: arr.astype("tTipo_de_dato")

In [13]:
#Cambaindo de tipo float a tipo entero
arr = np.array([1.1, 2.1, 3.1]) #Aqui es de tipo (float)
newarr = arr.astype('i') #Usamos el metodo astype con el parametro ("i") para convertir a entero, se almacena en una nueva variable
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [15]:
#Cambaindo de tipo float a tipo entero
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int) #Usamos el metodo astype con el parametro (int) para convertir a entero, se almacena en una nueva variable
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [17]:
#Cambie el tipo de datos de entero a booleano:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool) #Usamos el metodo astype con el parametro (bool) para convertir a boolean, se almacena en una nueva variable
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [19]:
#Cambie el tipo de datos de entero a booleano:
arr = np.array([1, 0, 3])
newarr = arr.astype("b") #Usamos el metodo astype con el parametro ("b") para convertir a boolean, se almacena en una nueva variable
print(newarr)
print(newarr.dtype)

[1 0 3]
int8
