# ***Metodos Copy vs View en una matriz (array) en NumPy***

❓ ***¿Cual es la diferencia entre copy y view en una matriz?***

🟡 ***Es que la copy es una nueva matriz y la view es solo una vista de la matriz original.***

🟡 ***La matriz de la (copy) tiene los datos  y cualquier cambio realizado en la matriz (copy) no afectará la matriz original, y cualquier cambio realizado en la matriz original no afectará a la matriz (copy).***

🟡 ***La matriz de la (view) no tiene los datos, cualquier cambio realizado en la matriz (view) afectará a la matriz original, y cualquier cambio realizado en la matriz original afectará a la matriz (view).***

> ###  ⚠️ ***Metodo: Copy()***

> 🟢 ***Haciendo cambios en la matriz original***

In [2]:
import numpy as np
#Haga una copia, cambie la matriz original y muestre ambas matrices:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy() #Aqui se copia la matriz original y se crea una nueva y se alamacena en una nueva variable
arr[0] = 42 #Se modifico el elemento de la posicion #0 de la matriz original
#Los cambios que hicimos en la matriz copia no afecta a la matriz original
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


> 🟢 ***Haciendo cambios en la matriz (copy)***

In [5]:
import numpy as np
#Haga una copia, cambie la matriz original y muestre ambas matrices:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy() #Aqui se copia la matriz original y se crea una nueva y se alamacena en una nueva variable
x[0] = 42 #Se modifico el elemento de la posicion #0
#Los cambios que hicimos en la matriz copia no afecta a la matriz original
print(arr)
print(x)

[1 2 3 4 5]
[42  2  3  4  5]


> ###  ⚠️ ***Metodo: View()***

> 🟢 ***Haciendo cambios en la matriz original***

In [3]:
#Cree una vista, cambie la matriz original y muestre ambas matrices:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view() #Usamos el metodo
arr[0] = 42 #Se modifico el elemento de la posicion #0 de la matriz original
#Los cambios que hicimos en la matriz original tambien afectaron a la matriz view
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


> 🟢 ***Haciendo cambios en la matriz (view)***

In [4]:
#Cree una vista, cambie la vista y muestre ambas matrices:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view() #Usamos el metodo
x[0] = 31 #Se modifico el elemento de la posicion #0 de la matriz view
#Los cambios que hicimos en la matriz original tambien afectaron a la matriz view
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


> ###  ⚠️ ***Como comprobar si una matriz es propietaria de sus datos***

✅ ***Las matrices creadas por (copy) SI son propietarias de sus datos***

✖️ ***Las matrices creadas por (view) NO son propietarias de sus datos***

💡 ***Usando el atributo: base***

❓ ***Este atributo devuelve como resultado (None) si la matriz posee los datos y si no los posee te va a regresar la Matriz original***

In [5]:
#Imprima el valor del atributo base para verificar si una matriz posee sus datos o no:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy() #Devolvio (None) porque las matrices creadas con (copy) SI poseen sus datos
y = arr.view() #Devolvio (La matriz) porque las matrices creadas con (view) NO poseen sus datos

print(x.base)
print(y.base)

None
[1 2 3 4 5]
